# Site Settings
title: Jose Alex
url: 'https://josevacha.github.io/online/'
baseurl: '/online' #change it according to your repository name
about: True # set to False or comment line if you want to remove the "How to use?" in the sidebar


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Jose Aex
tagline: Data Professional
pic: profile.jpg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'A technology enthusiast who is always looking for emerging trends in technology and business to solve real-world business problems. Currently playing a key role in Product Development and customer success. The key responsibilities include but are not limited to building growth plans for the digital solutions practices, aligned to organizational objectives and thus helping customers reimagine their business.
A seasoned data engineer and a python developer with experience in building data pipelines and integrating solutions for developing and delivering solutions in different domains. The profile goes through a series of projects delivered in different domains, a few solutions are business problem-centric and others are solutions engineered & delivered as a platform to achieve an end-to-end business process automation
You can download my resume <a href="//github.com/josevacha/online/raw/master/Jose%20Alex.pdf" target="_blank">HERE</a>.'

#sidebar links
email: mail2josephalex@gmail.com  
phone: 8050001023
website: josevacha.github.io/online/ #do not add http://
linkedin: josealex
github: josevacha

#Update all the sections by editing the files inside _data folder.

# uncomment the next line, if you want the education section displayed in main instead of the sidebar
#education_in_main: True

# Tracker
#analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
